INSERT INTO memes VALUES(NULL,"u1","a1",0,"t1","suny money funny",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"u2","a2",0,"t2","sunny money sad",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"u3","a3",0,"t3","money happy",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"u4","a3",0,"t4","money nil fuck",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"dsad","asdsad",0,"adas","funny crazy ",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"url1","dssad",0,"sadsa","dasdsa",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"url1","Darius",0,"url11","funny boring",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"last ural","10",0,"10","10",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"dasd","asdasd",0,"asdsadas","5 5 5 5",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"dasdas","Dasda",0,"zzzz","5 5",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.ineedmotivation.com/blog/wp-content/uploads/2007/08/laziness.jpg","Darius",0,"I am not lazy but crazy","I am not lazy but crazy  saving mode energy",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.ineedmotivation.com/blog/wp-content/uploads/2007/08/laziness.jpg","Darius",0,"A lazy smurf","smurf lazy fucking lazy",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.ineedmotivation.com/blog/wp-content/uploads/2007/08/laziness.jpg","Darius",0,"I can but I won't","can want cat lazy ratarded lazy lazy lazy lazy ",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.ineedmotivation.com/blog/wp-content/uploads/2007/08/laziness.jpg","Darius",0,"Fucking lazy","lazy button",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.ineedmotivation.com/blog/wp-content/uploads/2007/08/laziness.jpg","Darius",0,"A lazy fat cat","fat cat lazy lazy",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.ineedmotivation.com/blog/wp-content/uploads/2007/08/laziness.jpg","D",0,"I am lazy and I know it","lazy know it I retarded",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.ineedmotivation.com/blog/wp-content/uploads/2007/08/laziness.jpg","Darius",0,"Lazy bitch","lazy bitch blonda buna ",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.ineedmotivation.com/blog/wp-content/uploads/2007/08/laziness.jpg","Darius",0,"Sleep lazy","sleep lazy chair",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://thumbs.dreamstime.com/z/lazy-pig-1426866.jpg","Darius",0,"Lazy pig","pig lazy fat",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://thumbs.dreamstime.com/z/lazy-pigs-37716451.jpg","Darius",0,"The laziest pig","pig dirty fat lazy",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.featurepics.com/FI/Thumb300/20061101/Lazy-Pig-126094.jpg","Darius",0,"Lazy pig 2","pig lazy black",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://animationsa2z.com/attachments/Image/lovequote/love1.gif","DArius",0,"Love","the most important thing in my life is love",0,0,0,NULL,NULL);
