INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/yao-ming.jpg","Radu",0,"Yao Ming Face / Bi**h Please!","jpg jpeg yao ming face bitch please lol meme",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/fyeah.jpg","Radu",0,"F**k Yeah!","jpg jpeg png fuck yeah meme arrogance mighty might",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/if-you-know-what-i-mean.png","Radu",0,"If you know what I mean!","jpeg jpg png mr bean horny perv ero if you know what i mean",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/me-gusta.jpg","Radu",0,"Me Gusta!","jpeg jpg png me gusta lol retarded meme",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/true-story.png","Radu",0,"True Story.","jpeg jpg png barney stinson true story arrogance celebrity",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/troll.png","Radu",0,"Troll face / Problem?","jpeg jpg png troll face problem joke kidding lol",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/trolldad.jpg","Radu",0,"Troll Dad","joeg jpg png troll dad retarded son joke family",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/troll-mom.png","Radu",0,"Troll Mom","jpeg jpg png troll mom retarded mom joke family son lol",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/challenge.jpg","Radu",0,"Challenge Accepted","jpeg jpg png determined challenge accepted determination competition",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/computer-face.jpg","Radu",0,"Computer Reaction Face","jpeg jpg png computer reaction face serious what",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/derp-happy.png","Radu",0,"Happy Derp","jpeg jpg png retarded happy derp lol wtf idiot",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/derp2.jpg","Radu",0,"Derp 2","jpeg jpg png derp 2 idiot lol face",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/derp3.jpg","Radu",0,"Thinking","jpeg jpg png thinking meme face hmm smart",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/derp4.png","Radu",0,"Happy face","jpeg jpg png idiot face happy laugh ahaha",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/angry-derp.jpg","Radu",0,"Angry Face","jpeg jpg png angry face serious damn upset",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/cereal-guy.jpg","R",0,"Cereal Guy","jpeg jpg png cereal guy spit amaze amazed stupefy wtf lol face",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/cereal-guy-2.jpg","Radu",0,"Cereal Guy 2","jpeg jpg png cereal guy 2 lol wtf serious face",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/cereal-guy-3.jpg","Radu",0,"Cereal Guy 3","jpeg png jpg cereal guy retarded stupefy amazed amaze lol wtf face",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/begging-guy.jpg","Radu",0,"Beggin Guy","jpeg jpg png begging guy beg please sad",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/actually-its-not-ok.jpg","Radu",0,"Actually it's not ok","jpeg jpg png actually it is not okay ok sad shocked stupefy stupefied",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/derpina.png","Radu",0,"Derpina","jpg jpeg png derpina face meme girl",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/derpina2.png","Radu",0,"Derpina 2","jpeg jpg png blonde derpina girl",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/derpina3.jpg","Radu",0,"Derpina 3","jpg jpeg derpina girl retarded face",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/raisins_face.jpg","Radu",0,"Oh Crap! / OMG!","jpg oh crap omg stupefied stupefy wtf scared scary",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/being-an-x.jpg","Radu",0,"Being an x","jpg jpeg being an x ex pfff lip bite",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/forever-alone.jpg","Radu",0,"Forever Alone","jpg jpeg forever alone meme sad lonely cry",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/determined-guy.png","Radu",0,"Determined Guy","png determined guy serious confident",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/dude-come-on.png","Radu",0,"Dude, come on","png dude come on lol really bored",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/genius.png","Radu",0,"Genius","png genius smart idiot retard",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/fap-guy.png","Radu",0,"Fap Guy","fap guy png lol wtf gross porn",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/like-a-sir.jpg","Radu",0,"Like a sir!","jpg jpeg like a sir gentleman arrogance elegance drink",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/lol-guy.jpg","Radu",0,"LOL","jpg jpeg lol guy troll trololo",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/no.jpg","Radu",0,"No!","jpg jpeg no guy nooo deny",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/not-bad.jpg","Radu",0,"Not bad!","jpg jpeg not bad obama barrack pretty cool",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/okay.jpg","Radu",0,"Okay","jpg jpeg okay guy fine sad really",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/oh-stop-it-you.jpg","Radu",0,"Oh stop it, you!","jpg jpeg oh stop it you blush excited red cheeks",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/omg-run.jpg","Radu",0,"OMG! RUN!","jpeg jpg omg run wtf lol scared trololo",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/PFFFFT.png","Radu",0,"PFFFTTTCH!","png pf pff pfff pfffft pffft horny bastard",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/poker-face.jpg","Radu",0,"Poker face","jpg jpeg poker face lol what are you doing",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/rage.jpg","Radu",0,"FFFUUUUUUUU..","jpg jpeg fuck fuu fuuuu ffuu retard",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/sweet-jesus.jpg","Radu",0,"Sweet Jesus!","jpg jpeg sweet jesus what happened idiot",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/you-dont-say.png","Radu",0,"You don't say?!","png you dont say really sarcasm",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/y-u-no.jpg","Radu",0,"Y U NO..","jpg jpeg y why you u no dont wtf nicolas cage",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/son-i-am-disappointed.jpg","Radu",0,"Son, I'm disappointed","jpg jpeg arnold son im am disappointed dissapointment sad",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/are-you-serious.jpg","Radu",0,"Are you serious?","are you serious ice cube jpg jpeg",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/newspaper-guy.jpg","Radu",0,"Newspaper Guy","newspaper guy father dad glasses",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/milk-face.jpg","Radu",0,"Milk Face","milk face big eyes blue",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/mother-of-god.png","Radu",0,"Mother of God!","mother of god amazed glasses wtf",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/oh-god-why.jpg","Radu",0,"Oh GOD Why?","oh god why ashamed shame",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/now-kiss.png","Radu",0,"Now kiss!","now kiss evil lips",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/not-sure.jpg","Radu",0,"Not sure","not sure hmm insecure",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/shut-up-and-take-my-money.jpg","Radu",0,"Shut up and take my money!","shut up and take my money rich amazed",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/i-lied.jpg","Radu",0,"I lied!","i lied evil laugh moustache blue",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/watch-out.png","Radu",0,"Watch out!","watch out we got a badass over here black guy",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/whats-all-this-racket.jpg","Radu",0,"What's all this racket","racket, disappointment, son, father, fat",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/my-brain-is-full-of.jpg","Darius",0,"My brain is full of..","     jakie chan, carl sagan, responsitory, brain, fuck, mind is full of fuck, wtf jackie chan brain",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/overly-attached-girlfriend.jpg","Darius",0,"Overly attached girlfriend","overly attached girlfriend big eyes scary love",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/success-kid.png","Darius",0,"Success Kid","success kid yeah win victory",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/skeptical-baby.png","Darius",0,"Skeptical Kid","skeptical kid beautiful beauty",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/drunk-baby.jpg","Darius",0,"Drunk Kid","hilarious drunk kid funny",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/bad-luck-brian.jpg","Darius",0,"Bad luck Brian","bad luck brian virgin ugly",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/annoyed-picard.jpg","Darius",0,"Annoyed Piccard","annoyed piccard angry why x men",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/facepalm.jpg","Darius",0,"Face Palm","face palm wtf piccard x men stupid",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/that-escalated-quickly.jpg","Darius",0,"That escalated quickly!","will ferrell that escalated quickly",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/this-is-sparta.jpg","Darius",0,"This is SPARTA!","gerard gerrard butler this is sparta leonidas",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/cuteness-overload-l.png","Darius",0,"Cuteness Overload","cuteness overload big eyes cry cute",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/big-grin.png","Darius",0,"Big Grin","big grin laugh hilarious funny cry",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/aww-yea.jpg","Darius",0,"Aww Yeah!","aww yeah spiderman laugh evil",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/im-watching-you.jpg","Darius",0,"I'm watching you!","im am watching you suspect serious",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/you-are-dead-to-me.png","Darius",0,"You are dead to me!","you are dead to me angry",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/you-what-you-have-done.jpg","Darius",0,"You, what have YOU DONE?!","what have you done scared for life",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/you-win-this-time.jpg","Darius",0,"You win this time!","you win this time pissed angry",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/why-is-this-happening.jpg","Darius",0,"Why is this happening?","why y is this happening sad",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/x-all-the-y.png","Darius",0,"X all the Y","x all the y everybody all",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/eh-nois-guy.jpg","Darius",0,"Eh nois guy","eh nois guy smile",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/conga.jpg","Darius",0,"Conga!","conga dance everybody all",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/freddie-mercury.jpg","Darius",0,"Freddy Mercury","freddy mercury hand air",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/i-know-that-feel.jpg","Darius",0,"I know that feel","hug i know that feel sad",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/the-most-interesting-man-in-the-world.jpg","Darius",0,"The most interesting man","the most interesting man i dont always",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/sonic-dude.jpg","Darius",0,"Sonic dude","sonic dude middle finger",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/english-do-you-speak-it.jpg","Darius",0,"English! Do you speak it?","english do you speak it black actor gun",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/having-second-thoughts.png","Darius",0,"Having second thoughts","having second thoughts think",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/i-like-trains.jpg","Darius",0,"I like trains","i like trains lol wtf",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/death-note.jpg","Darius",0,"Death note","death note anime",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/crazy-mean-baby.jpg","Darius",0,"Mean Baby","mean baby angry cute",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/santa-troll.png","Darius",0,"Santa Troll","santa troll gift trololo lol",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/roto-ugly.jpg","Darius",0,"Ugly / Roto","ugly roto bleah",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/ragecomic.png","Darius",0,"Harp Derp","idiot harp derp face",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/so-good.png","Radu",0,"So Good","so good pff",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/pedobear.jpg","Darius",0,"Pedobear","pedobear pedo bear kids dangerous",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/awesome-face.png","Darius",0,"Awesome Face","awesome face retarded look",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/unamused.jpg","Darius",0,"Not amused","not amused unamused nope lol",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/annoying-orange.jpeg","Darius",0,"The annoying orange..","the annoying orange yellow teeth tooth eye",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/anonymouse.jpg","Darius",0,"Anonymouse","anonymouse hilarious",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/disaster-girl.jpg","Darius",0,"Disaster Girl","disaster girl evil look dangerous",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/bruce-lee.jpg","Darius",0,"Bruce Lee","bruce lee dangerous fighter",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/even-the-children.jpg","Darius",0,"Even the children","even the children sad life",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/Girls.png","Darius",0,"Girls","girls gossip pff",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/gtfo.gif","Darius",0,"GTFO","get the fuck out gtfo",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/nokia-3310.jpg","Darius",0,"Nokia 3310 - INDESTRUCTIBLE","nokia 3310 indestructible",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/what-if-i-told-you.jpg","Darius",0,"What if I told you?","matrix what if i told you black dude",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/im-6y-and-i-know-it.jpg","Radu",0,"I'm sexy and I know it!","im sexy and know it",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/hide-ya-kids.png","Radu",0,"Hide yo kids!","hide your kids wife rapist",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/ninja.jpg","Radu",0,"Ninja","ninja",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/who-was-flickering-the-lights.jpg","Radu",0,"Who was flickering the lights","dracula who was flickering the lights",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/fsjal.png","Radu",0,"fsjal","fsjal wtf lol what is this",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/pencil-guy.png","Radu",0,"Pencil Huy","pencil guy angry",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/the-italian-man-who-went-to-malta.jpg","Radu",0,"The italian man who went to Malta","italian malta fock on the table",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/nothing-to-do-here.jpg","Radu",0,"Nothing to do here!","nothing to do here rocket planet",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/im-gonna-do-an-internet.jpg","Radu",0,"I'm gonna do an internet!","i going internet rainbow retard",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/marv-scream.png","Radu",0,"Marv Scream","marv scream spider scary scared",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.memeurl.com/memes/unimpressed.png","Radu",0,"Not impresed..","not impresed gymnast gym mouth",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://i.memeful.com/media/post/kRpL7vR_700wa_0.gif","Radu",0,"Thumbs up - Taylor Swift","thumbs up taylor swift celebrity",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://i.memeful.com/media/post/WwlrNpR_700wa_0.gif","Radu",0,"I don't care","hilarious i dont care wtf",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://i.memeful.com/media/post/rw9ykEw_700wa_0.gif","Radu",0,"Deal with it","dr doctor cox deal with it",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/220/5039220.jpg","Dumi",0,"You expected fanservice but it was me Dio","you expected fanservice but it was me Dio",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://cmi.memecdn.com/561/4670561.jpgpg","Dumi",0,"Disgusting","disgusting",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://d3dsacqprgcsqh.cloudfront.net/photo/aZWq2jX_460sa_v1.gif","Dumi",0,"O hell no, cat","o hell no, cat",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://25.media.tumblr.com/64f44df27392c86b279ff35e94ff38eb/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"Noooope spongebob","noooope spongebob",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.paullee.com/misc/FacebookMemes/OpinionIsShit.jpg/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"Your opinion is shit saber","your opinion is shit saber",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/321/5080321.gifs/OpinionIsShit.jpg/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"Deadpool","deadpool",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://img-9gag-lol.9cache.com/photo/a9MPjNm_460sa_v1.gifpg/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"Complain box","complain box",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/444/4978444.jpgPjNm_460sa_v1.gifpg/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"Burn","burn",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/735/4992735_t.gifNm_460sa_v1.gifpg/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"Wut?","wut?",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/998/4942998.gififNm_460sa_v1.gifpg/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"Oh yes","oh yes",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/341/4999341.gififNm_460sa_v1.gifpg/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"I have a mighty need","i have a mighty need",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/652/5001652.gififNm_460sa_v1.gifpg/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"Serious","serious",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/94/5001094.giffifNm_460sa_v1.gifpg/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"Aham aham aham","aham aham aham",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/610/3575610.jpgifNm_460sa_v1.gifpg/tumblr_mwz8e5JJwP1smcbm7o1_500.gif","Dumi",0,"Dafuq is that","dafuq is that",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://www.themarysue.com/wp-content/uploads/2013/01/Jack-SparrowConfused.jpg1smcbm7o1_500.gif","Dumi",0,"Jack sparrow pe ganduri..","jack sparrow pe ganduri..",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/629/5015629.gifoads/2013/01/Jack-SparrowConfused.jpg1smcbm7o1_500.gif","Dumi",0,"Not funny man...not funny","not funny man...not funny",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/853/5027853.gifoads/2013/01/Jack-SparrowConfused.jpg1smcbm7o1_500.gif","Dumi",0,"Tell me more cat","tell me more cat",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/103/5023103.jpgoads/2013/01/Jack-SparrowConfused.jpg1smcbm7o1_500.gif","Dumi",0,"My father was quite the adventurer","my father was quite the adventurer",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/487/5033487.gifoads/2013/01/Jack-SparrowConfused.jpg1smcbm7o1_500.gif","Dumi",0,"This guy","this guy",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/700/5045700.jpgoads/2013/01/Jack-SparrowConfused.jpg1smcbm7o1_500.gif","Dumi",0,"Se intampla sa fiu expert in acest subiect","se intampla sa fiu expert in acest subiect",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://i29.tinypic.com/23r8r5t.jpg00.jpgoads/2013/01/Jack-SparrowConfused.jpg1smcbm7o1_500.gif","Dumi",0,"U mad?","u mad?",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://img.pandawhale.com/105081-that-doesnt-make-any-sense-gif-Cvcl.gifd.jpg1smcbm7o1_500.gif","Dumi",0,"That doesn't make any sense","that doesn't make any sense",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/643/5079643.gifesnt-make-any-sense-gif-Cvcl.gifd.jpg1smcbm7o1_500.gif","Dumi",0,"Compliment","compliment",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/306/5074306.jpgesnt-make-any-sense-gif-Cvcl.gifd.jpg1smcbm7o1_500.gif","Dumi",0,"That's not how it works you little shit","that's not how it works you little shit",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/537/5002537.gifesnt-make-any-sense-gif-Cvcl.gifd.jpg1smcbm7o1_500.gif","Dumi",0,"Reading","reading",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://static.fjcdn.com/comments/That+_71887712cb7bea439f6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"I like it, thor","i like it, thor",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/884/5118884.gif1887712cb7bea439f6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"You are platinum mad","you are platinum mad",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/174/5127174.gif1887712cb7bea439f6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Sasuke moustache","sasuke moustache",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://media.tumblr.com/tumblr_lzgegpCqi41qc35m6.pnga439f6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Dead eyes","dead eyes",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://img-9gag-lol.9cache.com/photo/aPyBA0Q_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Internal yelling","internal yelling",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/398/5158398.jpgBA0Q_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"My eyes!","my eyes!",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/515/5156515.gifBA0Q_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Nope","nope",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/830/5171830.gifBA0Q_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Who the hell do you think i am?","who the hell do you think i am?",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/56/5172056.jpgfBA0Q_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Okay just what?","okay just what?",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://img-9gag-lol.9cache.com/photo/aYpxQX7_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Fuck","fuck",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/889/5217889.jpgxQX7_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Bored smokeing","bored smokeing",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://img-9gag-lol.9cache.com/photo/aDwx7d9_460s_v1.jpgf6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"What the fuck is this?","what the fuck is this?",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://img-9gag-lol.9cache.com/photo/a9MpgDo_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Your soul is mine","your soul is mine",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/4/5310004.jpg9MpgDo_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Says here you are a little bitch","says here you are a little bitch",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/291/5324291.jpgpgDo_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Boobs, yes we like boobs","boobs, yes we like boobs",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://i.minus.com/ibnKUcCAh92qBg.gifjpgpgDo_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Aaaaaaaaaaaaaaaaaaaaaaaa","aaaaaaaaaaaaaaaaaaaaaaaa",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://i.cubeupload.com/BeHuMD.pnggifjpgpgDo_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"%VIL","EVIL",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://rs1ci.memecdn.com/697/5472697.jpgpgDo_460sa_v1.gif6fc35f93bce038.jpgpg1smcbm7o1_500.gif","Dumi",0,"Wakarimasen lol","wakarimasen lol",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://assets.diylol.com/hfs/ae5/b1b/cfa/resized/django-meme-generator-madam-you-had-my-curiosity-but-now-you-have-my-attention-1c91f2.jpg","Dumi",0,"At first you had my curiosity, now you have my attention","at first you had my curiosity, now you have my attention",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://img-9gag-lol.9cache.com/photo/aPygBXn_460s.jpggo-meme-generator-madam-you-had-my-curiosity-but-now-you-have-my-attention-1c91f2.jpg","Dumi",0,"Dafuq is this, dafuq is that","dafuq is this, dafuq is that",0,0,0,NULL,NULL);
INSERT INTO memes VALUES(NULL,"http://img-9gag-lol.9cache.com/photo/aZWnB8n_460sa.gifo-meme-generator-madam-you-had-my-curiosity-but-now-you-have-my-attention-1c91f2.jpg","Dumi",0,"Yes yes yeeeees!!!","yes yes yeeeees!!!",0,0,0,NULL,NULL);