# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea2289a3e3dce91262bb861cfb40a099cedd665f559bc8bd884a05ea84615936f49f351fe35a692c6b3591ba9cd4cb0c78bbbeed7b060650594433186f843f0c

test:
  secret_key_base: b5b6cbf653ad6c8924fb088aba043a05ed1819774af7747e9d90d7ebe00791a98affe588247646e5b0444f60b634875d4382472534768b3b0e2df191dc139bfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
